// <auto-generated />
namespace RentalManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedapplicationusertotenantandmanagertables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedapplicationusertotenantandmanagertables));
        
        string IMigrationMetadata.Id
        {
            get { return "201611081628164_Added application user to tenant and manager tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
